---
- name: Deploy Website on EC2 Instances with NGINX
  hosts: webservers
  become: yes
  gather_facts: yes

  vars:
    nginx_port: 80
    website_dir: /var/www/html

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Start and enable NGINX service
      systemd:
        name: nginx
        state: started
        enabled: yes

    - name: Remove default NGINX site
      file:
        path: "{{ website_dir }}/index.nginx-debian.html"
        state: absent

    - name: Create website directory
      file:
        path: "{{ website_dir }}"
        state: directory
        owner: www-data
        group: www-data
        mode: "0755"

    - name: Deploy HTML file
      copy:
        src: index.html
        dest: "{{ website_dir }}/index.html"
        owner: www-data
        group: www-data
        mode: "0644"
      notify:
        - restart nginx

    - name: Replace placeholder with the instance's hardcoded IP
      shell: |
        sed -i "s/YOUR_INSTANCE_IP_HERE/{{ ansible_host }}/" {{ website_dir }}/index.html
      args:
        executable: /bin/bash

    - name: Create health check endpoint
      copy:
        content: "healthy\n"
        dest: "{{ website_dir }}/health"
        owner: www-data
        group: www-data
        mode: "0644"

    - name: Test NGINX configuration
      command: nginx -t
      changed_when: false

    - name: Open firewall for HTTP traffic (if UFW is enabled)
      ufw:
        rule: allow
        port: "{{ nginx_port }}"
        proto: tcp
      ignore_errors: yes

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
